name: Reusable workflow

on:
        workflow_dispatch:
                inputs:
                        who-to-greet:
                                description: 'The person to greet'
                                required: true
                                default: 'World'
                outputs:
                        current-time:
                                description: 'The time when greeting.'
                                value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
        reusable-job:
                runs-on: ubuntu-latest
                steps:
                        - name: "Print a greeting"
                                run: echo "Hello ${{ inputs.who-to-greet }}"
                        - name: "Set time"
                                id: time
                                run: echo "time=$(date)" >> $GITHUB_OUTPUT